variables:
  REGISTRY: registry.gitlab.com

stages:
  - test
  - build

services:
  - docker:dind

test:
  image: node:8
  stage: test
  # add cache to 'node_modules' for speeding up builds
  cache:
    paths: 
      - node_modules/ # Node modules and dependencies
  script:
    - npm install
    - npm run lint

build_docker_x64:
  image: docker:latest
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t $REGISTRY/emilohman/node-smart-remote/x64 -f hosting/docker/Dockerfile.x64 .
    - docker push $REGISTRY/emilohman/node-smart-remote/x64
  only:
    - master
  tags:
    - docker

build_docker_rpi:
  image: balenalib/raspberrypi3-debian-node:8-jessie-build
  stage: build
  before_install:
    - sudo apt-get --quiet update --yes
    - sudo apt-get install --yes docker git
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t $REGISTRY/emilohman/node-smart-remote/rpi -f hosting/docker/Dockerfile.rpi .
    - docker push $REGISTRY/emilohman/node-smart-remote/rpi
  only:
    - master
  tags:
    - docker