variables:
  REGISTRY: gitlab.com:4567

stages:
  - test
  - build

test:
  image: node:8.9
  stage: test
  # add cache to 'node_modules' for speeding up builds
  cache:
    paths: 
      - node_modules/ # Node modules and dependencies
  script:
    - npm install
    - npm run lint

build_docker_x64:
  image: docker:latest
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t $REGISTRY/emilohman/node-smart-remote_x64 -f hosting/docker/Dockerfile.x64 .
    - docker push $REGISTRY/emilohman/node-smart-remote_x64
  only:
    - master
  tags:
    - docker

build_docker_rpi:
  image: docker:latest
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t $REGISTRY/emilohman/node-smart-remote_rpi -f hosting/docker/Dockerfile.rpi .
    - docker push $REGISTRY/emilohman/node-smart-remote_rpi
  only:
    - master
  tags:
    - docker