FROM hypriot/rpi-node:6.10.0

ENV NODE_ENV production
ENV USING_DOCKER true
RUN mkdir -p /opt/node-smart-remote
WORKDIR /opt/node-smart-remote

COPY package.json /opt/node-smart-remote
RUN npm install --production
COPY . /opt/node-smart-remote

CMD [ "npm", "start" ]
