FROM balenalib/raspberrypi3-debian-node:8-jessie-run

ENV NODE_ENV production
ENV USING_DOCKER true
WORKDIR /home/node

RUN cp /usr/share/zoneinfo/Europe/Stockholm /etc/localtime

COPY package.json /home/node
RUN npm install --production
COPY . /home/node

CMD [ "npm", "start" ]
