FROM balenalib/amd64-debian-node:10-stretch-run

ENV NODE_ENV production
ENV USING_DOCKER true
WORKDIR /home/node

RUN cp /usr/share/zoneinfo/Europe/Stockholm /etc/localtime

RUN install_packages git

COPY package.json package-lock.json /home/node/
RUN npm ci --production
COPY . /home/node

CMD [ "npm", "start" ]
